baseURL = "https://positiva-cali.vercel.app/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Positiva - Ecología [notas + noticias]"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params] 
mainSections = ["post","posts"]
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "12"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Lucfreelance"
  website = "https://lucfreelance.com/"
  email = "lucfreelance@gmail.com"
  facebook = "lucfreelance"
  instagram = "lucfreelance"
  youtube = "user/lucfreelance" # or channel/channelname
  twitter = "lucfreelance"
  linkedin = "lucfreelance"
  github = "lucfreelance"
  #gitlab = "lucfreelance"
  #bitbucket = "lucfreelance"
  #reddit = "lucfreelance"
  #xing = "lucfreelance"
  #stackoverflow = "users/lucfreelance/username"
  #snapchat = "lucfreelance"
  #soundcloud = "lucfreelance"
  #spotify = "lucfreelance"
  #bandcamp = "lucfreelance"
  #itchio = "lucfreelance"
  #vk = "lucfreelance"
  paypal = "lucfreelance"
  #telegram = "lucfreelance
  #500px = "lucfreelance"
  #codepen = "lucfreelance"
  #mastodon = "lucfreelance"
  #kaggle = "lucfreelance"
  #weibo = "lucfreelance"
  #slack = "lucfreelance"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notas"
    url = "/notas/"
    weight = 2

[[menu.main]]
    name = "Cosas"
    url = "/cosas/"
    weight = 3

[[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 5



